spring:
  datasource:
    generate-unique-name: false
    name: content
  h2:
    console:
      enabled: true

spotify:
  authorizeUri: https://accounts.spotify.com/authorize
youtube:
  springPlaylistId: PLbCvOPoX4TBkiXoIcVZnIvaEPNu571_zc